<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Your password was changed</title>
</head>
<body>
	<div style="margin-top: 10px">Greetings,</div>
	<br/>
	<div>Your password was changed. You can use your new password to sign in to your account.</div>
	<div>
		<h4>New Password: <span style="font-weight: bold;">${code}</span></h4>
	</div>
</body>
</html>